language: php

php:
  - 5.5

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install
  - chmod -R 777 storage
  - php artisan key:generate
  - php artisan migrate

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v

